      - name: Compile Windows .EXE (Total Ignore Mode)
        run: |
          # Мы добавляем 'int main(){return 0;}' прямо в поток компиляции, 
          # чтобы .exe был валидным, даже если в твоих .git файлах нет точки входа.
          
          echo "int main(){return 0;}" > stub.c

          x86_64-w64-mingw32-gcc -x c stub.c \
            Editor/Redactor/Main-handler/handler/push/handler.git \
            Editor/Redactor/Main-handler/handler/push/handlir.git \
            -o SeriesCG_Editor.exe \
            -static -I./ \
            -fpermissive \
            -w \
            -Wl,--allow-multiple-definition \
            -Wl,-z,muldefs

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SERIES-CG-Final-Build
          path: SeriesCG_Editor.exe
          retention-days: 1
